// frontend/src/components/ScaleCalibration.jsx
import React, { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import { projectsAPI } from '../api';

export default function ScaleCalibration({ projectId, pageNumber, onCalibrationSuccess }) {
  const [knownDistance, setKnownDistance] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [calibrationPoints, setCalibrationPoints] = useState([]);
  const [savedScaleFactor, setSavedScaleFactor] = useState(null);
  const [savedScaleLabel, setSavedScaleLabel] = useState('');

  useEffect(() => {
    const handleCalibrationPointsSelected = (event) => {
      const points = event.detail;
      setCalibrationPoints(points);
      toast.success('Two points selected. Enter the distance in feet.');
    };

    window.addEventListener('calibrationPointsSelected', handleCalibrationPointsSelected);
    return () => {
      window.removeEventListener('calibrationPointsSelected', handleCalibrationPointsSelected);
    };
  }, []);

  const handleStartTwoPointCalibration = () => {
    setCalibrationPoints([]);
    toast.success('Click two points on the plat to calibrate scale');
    window.dispatchEvent(new CustomEvent('startCalibration'));
  };

  const handleCancelCalibration = () => {
    setCalibrationPoints([]);
    toast.success('Calibration cancelled');
    window.dispatchEvent(new CustomEvent('cancelCalibration'));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!knownDistance || isNaN(knownDistance) || knownDistance <= 0) {
      toast.error('Enter a valid distance in feet');
      return;
    }
    if (calibrationPoints.length !== 2) {
      toast.error('Select exactly two points');
      return;
    }

    setIsLoading(true);
    try {
      const dx = calibrationPoints[1].x - calibrationPoints[0].x;
      const dy = calibrationPoints[1].y - calibrationPoints[0].y;
      const distancePdfUnits = Math.sqrt(dx * dx + dy * dy);
      const scaleFactor = parseFloat(knownDistance) / distancePdfUnits;

      const calibrationData = {
        method: 'two_point',
        page_number: pageNumber,
        scale_factor: scaleFactor,
        point_a: calibrationPoints[0],
        point_b: calibrationPoints[1],
        known_distance_ft: parseFloat(knownDistance),
      };

      await projectsAPI.createCalibration(projectId, calibrationData);

      toast.success('Scale calibration saved');
      setSavedScaleFactor(scaleFactor);
      setSavedScaleLabel(`${knownDistance} ft between points → ${scaleFactor.toFixed(6)} ft per PDF unit`);

      window.dispatchEvent(new CustomEvent('calibrationSaved', { detail: { points: calibrationPoints, scaleFactor } }));

      setCalibrationPoints([]);
      setKnownDistance('');
      onCalibrationSuccess?.({ points: calibrationPoints, scaleFactor });
    } catch (error) {
      toast.error(error.response?.data?.detail || 'Failed to save calibration');
    } finally {
          onCalibrationSuccess?.({ points: calibrationPoints, scaleFactor });
    }
  };

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h3 className="text-lg font-semibold mb-4">Scale Calibration (Two-Point)</h3>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleStartTwoPointCalibration}
              disabled={isLoading || (!!savedScaleFactor && calibrationPoints.length === 0)}
              className="button-secondary flex-1 disabled:opacity-50"
            >
              Click to Select Two Points
            </button>
            {calibrationPoints.length > 0 && (
              <button
                type="button"
                onClick={handleCancelCalibration}
                className="px-3 py-2 rounded bg-gray-300 text-gray-700 hover:bg-gray-400"
              >
                Cancel
              </button>
            )}
          </div>
          {calibrationPoints.length > 0 && (
            <p className="text-sm text-gray-600 mt-2">
              {calibrationPoints.length} point{calibrationPoints.length !== 1 ? 's' : ''} selected
            </p>
          )}
        </div>

        {calibrationPoints.length === 2 && (
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Distance Between Points (feet) *
            </label>
            <input
              type="number"
              step="0.01"
              value={knownDistance}
              onChange={(e) => setKnownDistance(e.target.value)}
              placeholder="e.g., 200"
              className="input-field w-full"
              disabled={isLoading}
            />
          </div>
        )}

        <button
          type="submit"
          disabled={isLoading || calibrationPoints.length !== 2 || !knownDistance}
          className="button-primary w-full disabled:opacity-50"
        >
          {isLoading ? 'Saving...' : 'Save Calibration'}
        </button>

        {savedScaleFactor && (
          <p className="text-sm text-gray-700 mt-2">Scale: {savedScaleLabel || `${savedScaleFactor.toFixed(6)} ft per PDF unit`}</p>
        )}
      </form>

      {savedScaleFactor && (
        <div className="mt-4 p-3 bg-gray-100 rounded border border-gray-200 text-sm text-gray-800">
          Saved Scale: {savedScaleLabel || `${savedScaleFactor.toFixed(6)} ft per PDF unit`}
        </div>
      )}
    </div>
  );
}

// frontend-angular/src/app/components/scale-calibration/scale-calibration.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { StateService } from '../../core/services/state.service';

@Component({
  selector: 'app-scale-calibration',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-4">
      <h3 class="text-lg font-semibold">Scale Calibration</h3>
      <div class="space-y-2">
        <label class="block">
          <input 
            type="radio" 
            name="calibration" 
            value="twopoint"
            [(ngModel)]="calibrationMethod"
            (change)="onMethodChange()"
          >
          Two-Point Calibration
        </label>
        <label class="block">
          <input 
            type="radio" 
            name="calibration" 
            value="manual"
            [(ngModel)]="calibrationMethod"
            (change)="onMethodChange()"
          >
          Manual Scale
        </label>
      </div>

      <div *ngIf="calibrationMethod === 'twopoint'" class="space-y-2">
        <p class="text-sm text-gray-600">Click two points on the PDF, then enter the distance between them</p>
        <button 
          (click)="startCalibration()"
          [disabled]="calibrating"
          class="px-4 py-2 bg-blue-600 text-white rounded disabled:opacity-50"
        >
          {{ calibrating ? 'Waiting for points...' : 'Start Calibration' }}
        </button>
        <div *ngIf="calibrationPoints.length > 0" class="text-sm text-gray-600">
          Points selected: {{ calibrationPoints.length }}/2
        </div>
      </div>

      <div *ngIf="calibrationMethod === 'manual'" class="space-y-2">
        <label class="block">
          <span class="text-sm">Scale (pixels per foot):</span>
          <input 
            type="number" 
            [(ngModel)]="manualScale"
            class="w-full px-2 py-1 border rounded"
            step="0.1"
          >
        </label>
      </div>

      <button 
        (click)="saveCalibration()"
        class="w-full px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
      >
        Save Calibration
      </button>

      <div *ngIf="savedCalibration" class="p-3 bg-green-50 border border-green-200 rounded">
        <p class="text-sm"><strong>Scale Factor:</strong> {{ savedCalibration.scale_factor }}</p>
        <p class="text-sm"><strong>Method:</strong> {{ savedCalibration.method }}</p>
      </div>
    </div>
  `
})
export class ScaleCalibrationComponent {
  @Input() projectId: number | null = null;
  @Output() calibrationChanged = new EventEmitter<any>();

  calibrationMethod = 'twopoint';
  calibrating = false;
  calibrationPoints: { x: number; y: number }[] = [];
  manualScale = 1;
  savedCalibration: any = null;

  constructor(
    private apiService: ApiService,
    private stateService: StateService
  ) {
    window.addEventListener('calibrationPointsSelected', (event: any) => {
      this.calibrationPoints = event.detail;
      this.onCalibrationPointsSelected();
    });
  }

  startCalibration() {
    this.calibrating = true;
    this.calibrationPoints = [];
  }

  onMethodChange() {
    this.calibrationPoints = [];
  }

  onCalibrationPointsSelected() {
    this.calibrating = false;
    if (this.calibrationPoints.length === 2) {
      const distance = Math.sqrt(
        Math.pow(this.calibrationPoints[1].x - this.calibrationPoints[0].x, 2) +
        Math.pow(this.calibrationPoints[1].y - this.calibrationPoints[0].y, 2)
      );
      const knownDistance = prompt('Enter the real-world distance (in feet):');
      if (knownDistance) {
        this.calculateScaleFactor(distance, parseFloat(knownDistance));
      }
    }
  }

  calculateScaleFactor(pixelDistance: number, realDistance: number) {
    this.manualScale = pixelDistance / realDistance;
  }

  saveCalibration() {
    if (!this.projectId) return;

    const calibration = {
      page_number: 1,
      method: this.calibrationMethod,
      scale_factor: this.manualScale,
      known_distance_ft: this.calibrationMethod === 'twopoint' ? null : null
    };

    this.apiService.saveScaleCalibration(this.projectId, calibration).subscribe(
      (saved) => {
        this.savedCalibration = saved;
        this.stateService.setScaleCalibration(saved);
        this.calibrationChanged.emit(saved);
      }
    );
  }
}
